### ISSUE TITLE
Place lichen.vim under colors/ ?

### ISSUE THREAD

**Issue by lesguillemets** [jyalim/lichen#1]
Hi, 

Some plugin managers assume that repositories for vim plugins have the same directory structures as seen under `~/.vim/`. So, if `lichen.vim` is placed under `colors/` in this repository, it is easier for them to handle this. For example, for `neobundle` I use, one can install this colorscheme by just `NeoBundle 'hellabyte/lichen'`. This is not a must, but please concider changing the directory structure.

This colorscheme is pleasantly designed and I like it. Thank you!

**Comment by jyalim** [comment]
Thank you for bringing this up. I have yet to use a plugin manager so I didn't think about this facet. I have made the changes and it should work with plugin managers now.

**Comment by lesguillemets** [comment]
Thank you!
